# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8080:80"

